-- Smart Scanner Database Schema v1.1
-- Initial migration with all core tables

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Patterns supported in the system
CREATE TABLE IF NOT EXISTS public.patterns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,              -- 'sma150_bounce'
  name TEXT NOT NULL,                     -- 'SMA-150 Bounce'
  description TEXT,
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pattern configs (per pattern)
CREATE TABLE IF NOT EXISTS public.pattern_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pattern_code TEXT REFERENCES public.patterns(code) ON DELETE CASCADE,
  key TEXT NOT NULL,                      -- e.g. 'sma_window', 'touch_tolerance_pct'
  value JSONB NOT NULL,
  UNIQUE(pattern_code, key)
);

-- Signals generated by scans
-- v1.1 rule: for 'sma150_bounce' we only persist rows where verdict='ENTER'
CREATE TABLE IF NOT EXISTS public.signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol TEXT NOT NULL,
  pattern_code TEXT REFERENCES public.patterns(code),
  verdict TEXT NOT NULL,                  -- 'ENTER' | 'AVOID' (ENTER-only persisted for sma150_bounce)
  probability NUMERIC,                    -- optional (for ML patterns)
  score NUMERIC,                          -- deterministic score 0..1
  reason TEXT,                            -- short human summary
  details JSONB,                          -- raw measurements (touch distance, bounce count, etc)
  snapshot_date DATE NOT NULL,            -- bar date used for decision
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(symbol, pattern_code, snapshot_date)
);

-- Indexes for signals table
CREATE INDEX IF NOT EXISTS signals_symbol_created_idx ON public.signals(symbol, created_at DESC);

-- Partial index to speed ENTER reads for sma150_bounce
CREATE INDEX IF NOT EXISTS signals_enter_idx
ON public.signals (created_at DESC)
WHERE verdict = 'ENTER' AND pattern_code = 'sma150_bounce';

-- Backtest results (optional)
CREATE TABLE IF NOT EXISTS public.backtests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pattern_code TEXT REFERENCES public.patterns(code),
  as_of_date DATE NOT NULL,
  horizon_days INT NOT NULL,
  threshold NUMERIC,
  total INT, 
  success INT, 
  fail INT,
  success_rate NUMERIC,
  avg_max_gain NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seen-today cache to avoid rescans
CREATE TABLE IF NOT EXISTS public.daily_seen (
  seen_date DATE NOT NULL,
  symbol TEXT NOT NULL,
  PRIMARY KEY (seen_date, symbol)
);

-- Ticker catalog (cache from FMP list)
CREATE TABLE IF NOT EXISTS public.tickers (
  symbol TEXT PRIMARY KEY,
  name TEXT,
  exchange TEXT,
  market_cap NUMERIC,
  last_volume NUMERIC,
  is_active BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Model registry (future ML stages)
CREATE TABLE IF NOT EXISTS public.models (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pattern_code TEXT REFERENCES public.patterns(code),
  version TEXT NOT NULL,
  path TEXT NOT NULL,                      -- storage path
  metrics JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(pattern_code, version)
);

-- Batch telemetry per scan run (no per-ticker Avoid rows stored)
CREATE TABLE IF NOT EXISTS public.pattern_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pattern_code TEXT NOT NULL,
  run_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  scanned_count INT NOT NULL,
  enter_count INT NOT NULL,
  rejected_count INT NOT NULL,
  notes TEXT
);

-- Index for pattern runs
CREATE INDEX IF NOT EXISTS pattern_runs_recent_idx
ON public.pattern_runs (pattern_code, run_started_at DESC);

-- Insert initial pattern
INSERT INTO public.patterns (code, name, description, is_enabled)
VALUES (
  'sma150_bounce',
  'SMA-150 Bounce',
  'Identifies stocks that respect their 150-day moving average and show bounce potential',
  true
) ON CONFLICT (code) DO NOTHING;

-- Insert default configuration for SMA-150 bounce pattern
INSERT INTO public.pattern_configs (pattern_code, key, value) VALUES
('sma150_bounce', 'sma_window', '150'),
('sma150_bounce', 'touch_tolerance_pct', '5.0'),
('sma150_bounce', 'lookback_days_for_history', '365'),
('sma150_bounce', 'min_bounces', '3'),
('sma150_bounce', 'min_avg_rebound_pct', '5.0'),
('sma150_bounce', 'rebound_window_days', '10'),
('sma150_bounce', 'min_volume_sma_ratio', '1.2'),
('sma150_bounce', 'min_liquidity_filters', '{"min_market_cap": 200000000, "min_daily_volume": 200000}')
ON CONFLICT (pattern_code, key) DO NOTHING;
